### ISSUE TITLE
Problem with placeholder.grid.scss

### ISSUE THREAD

**Issue by sstuppi** [Horttcore/WordPress-Theme-Boilerplate#1]
The file placeholder.grid.scss can't access the mixins made in custom-media-queries.scss.
Terminal outputs the error: no mixin named ...

**Comment by Horttcore** [comment]
These are no mixins, this is plain CSS.

```@custom-media --adminbar--sticky (min-width: 37.5em);```

https://drafts.csswg.org/mediaqueries-5/#custom-mq

**Comment by Horttcore** [comment]
This part is a WIP as there is no post-css plugin installed yet.
